### ISSUE TITLE
404 and Unauthorized API Errors

### ISSUE THREAD

**Issue by DrewWalkup** [runpod/runpod-python#258]
**Describe the bug**
Using the provided code in this repo, attempting to use Serverless API endpoint results in 404 when using run() method and Unauthorized when using the get_endpoints() method.

**To Reproduce**
1. Create a Runpod account
2. Create API keys
3. Launch a Serverless template
4. Copy/pasta code from this repo
5. Input your endpoint ID and api key
6. Run
7. Watch errors roll in

**Expected behavior**
A response from my API code, error or not, that is not an unsuccessful call.

**Screenshots**
Lol

**Desktop (please complete the following information):**
 - OS: OSX Sonoma
 - Current PIP install of Runpod module
 - Python 3.11
 - Functional internet connection

**Additional context**
Would like this to work so I don't have to use AWS.

**Comment by justinmerrell** [comment]
We would love to have this work for you as well so you don't have to use AWS either :) 

There's not much I can do with the "lol" screenshot, however, if you have an endpoint ID or additional context to work from I am sure we can resolve your issues quickly.

**Comment by DrewWalkup** [comment]
I appreciate you handling my frustration with grace.

Docker is and apparently always will be a disaster for me, I gave up on
that after finding this guide:
https://blog.runpod.io/runpod-serverless-no-docker-stress/

I was finally able to get a 200 response code, but then could not return a
proper json response while waiting for the instance to complete.

However, the nail in the coffin was when I jumped back to my endpoint
dashboard, I found two instances running for 2-3 minutes each without being
prompted to do so. Is this a common issue?

I decided to give up on it for the evening, but I don't think I can pursue
serverless with runpod if instances are going to run in the background and
eat up my $$.

Lots of problems to solve here (e.g. json response error, unprompted
instances), happy for any insight you can provide.

**Comment by justinmerrell** [comment]
No worries, I too struggled when first starting with docker. If you have not already joined our Discord I would encourage you to do so, it is easier to provide assistance there. 

From what I can make out, it appears that you created a serverless endpoint, and sent a request but at some point, the worker failed to process or get the request. Since the request was still in the queue our system likely tried to spin up an additional worker to respond to the request. 

The first step would be to share the code you are running so we can make sure everything looks correct there.

Note: Since this is not an issue directly related to the contents of this repository (runpod-python) I am going to close the issue, however I can continue to provide assistance if you respond even after it is marked as closed :)
