### ISSUE TITLE
Counting Failiures Correctly

### ISSUE THREAD

**Issue by m-pektas** [runpod/runpod-python#299]
I want to catch all fail cases in runpod and monitor from the metrics dashboard. What should i do for this ? I think i have two options now;

- Option 1: return "error" keyword in response
- Option 2: raise Exception directly in handler function.

are these options correct ? Which option is better ? are there any another options about it ?

**Comment by ashleykleynhans** [comment]
## Option 1
If you use the `error` key, the value needs to be an `str`.  It does not handle `dict`, and if you use a `dict`, it will result in the job returning as `COMPLETED` instead of `FAILED` without any output, so if you go this route, the best way to handle it is as follows:

```python
return {
   "error": "Some error message string",
   "output": {
     "detail": "Some detail"  
   }
}
```

You can also optionally refresh the worker as follows:

```python
return {
   "error": "Some error message string",
   "output": {
     "detail": "Some detail"  
   },
   "refresh_worker": True
}
```

## Option 2
This is also fine, the SDK will handle the exception for you and correctly mark the job as `FAILED`, but you won't be able to use `refresh_worker` if you need that.

**Comment by ashleykleynhans** [comment]
By the way, the RunPod Discord is more suitable for asking questions, thats why you couldn't find a suitable tag.  Github is for logging bugs and requesting new features, not for asking questions, Discord is there for questions.

**Comment by m-pektas** [comment]
Thanks @ashleykleynhans.

As I understand, when I use the following return statement, runpod labeled my process as FAILED. And, If I want to refresh worker, I can use `refresh_worker` parameter.

```
return {
   "error": "Some error message string",
   "output": {
     "detail": "Some detail"  
   }
}
```

**Comment by ashleykleynhans** [comment]
> Thanks @ashleykleynhans.
> 
> As I understand, when I use the following return statement, runpod labeled my process as FAILED. And, If I want to refresh worker, I can use `refresh_worker` parameter.
> 
> ```python
> return {
>    "error": "Some error message string",
>    "output": {
>      "detail": "Some detail"  
>    }
> }
> ```

Correct!
